# Nome da Actions:
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gleidersondev #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Escreve a variável de ambiente BUILD_STATUS no arquivo GITHUB_STATE.
      - name: Set environment variable
        run: echo "BUILD_STATUS=success" >> $GITHUB_STATE

      # Escreve os arquivos gerados nos diretórios de saída.
      - name: Write output files
        run: |
          echo "snake-gif=$snake-gif" >> $GITHUB_OUTPUT
          echo "snake-gif-svg=$snake-gif-svg" >> $GITHUB_OUTPUT

      # Usa a action crazy-max/ghaction-github-pages para fazer o deploy dos arquivos gerados para o branch output.
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.7.2
        with:
          build_dir: dist
          branch: output
          token: ${{ secrets.GITHUB_TOKEN }}
